name: Run tests

on:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  php-tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        php: [8.0, 7.4, 7.3]
        laravel: [8.*, 7.*, 6.*, 5.8.*, 5.7.*, 5.6.*]
        os: [ubuntu-latest]
        include:
          - laravel: 8.*
            testbench: 6.*
          - laravel: 7.*
            testbench: 5.*
          - laravel: 6.*
            testbench: 4.*
          - laravel: 5.8.*
            testbench: 3.8.*
          - laravel: 5.7.*
            testbench: 3.7.*
          - laravel: 5.6.*
            testbench: 3.6.*
        exclude:
          - laravel: 5.7.*
            php: 7.4
          - laravel: 5.6.*
            php: 7.4
          - laravel: 5.5.*
            php: 7.4
          - laravel: 5.8.*
            php: 8.0
          - laravel: 5.7.*
            php: 8.0
          - laravel: 5.6.*
            php: 8.0

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, dom, fileinfo
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --prefer-stable --prefer-dist --no-interaction --ignore-platform-reqs
      - name: Execute tests
        run: vendor/bin/phpunit
